//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disa.Framework.Telegram.Mobile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disa.Framework.Telegram.Mobile.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is looking good..
        /// </summary>
        internal static string TelegramAllGood {
            get {
                return ResourceManager.GetString("TelegramAllGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate an authentication. Please try again..
        /// </summary>
        internal static string TelegramAuthGenerationFailedMessage {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Generation Failed.
        /// </summary>
        internal static string TelegramAuthGenerationFailedTitle {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string TelegramCode {
            get {
                return ResourceManager.GetString("TelegramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered has expired. Please send yourself another..
        /// </summary>
        internal static string TelegramCodeCodeExpired {
            get {
                return ResourceManager.GetString("TelegramCodeCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeCodeInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Please try again..
        /// </summary>
        internal static string TelegramCodeError {
            get {
                return ResourceManager.GetString("TelegramCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeFirstNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeFirstNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a code to verify Telegram..
        /// </summary>
        internal static string TelegramCodeInvalidMessage {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Code.
        /// </summary>
        internal static string TelegramCodeInvalidTitle {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeLastNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeLastNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 6 character code provided from Telegram below..
        /// </summary>
        internal static string TelegramCodeManualEnter {
            get {
                return ResourceManager.GetString("TelegramCodeManualEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeNumberInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your code does not come through, please click the &apos;Verification&apos; tab and activate Telegram with the &apos;via Phone&apos; option..
        /// </summary>
        internal static string TelegramCodeSentNotComingSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentNotComingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram activation has been contacted! You&apos;ll be phoned shortly with an activation code..
        /// </summary>
        internal static string TelegramCodeSentViaPhone {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram activation has been contacted! You&apos;ll be messaged shortly with an activation code..
        /// </summary>
        internal static string TelegramCodeSentViaSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string TelegramCodeTitle {
            get {
                return ResourceManager.GetString("TelegramCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the number [number] correct? This is what we&apos;ll use to verify your Telegram account..
        /// </summary>
        internal static string TelegramConfirmNumberMessage {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Number.
        /// </summary>
        internal static string TelegramConfirmNumberTitle {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram is a messaging app with a focus on speed and security. It&apos;s super-fast, simple, secure and free..
        /// </summary>
        internal static string TelegramDescription {
            get {
                return ResourceManager.GetString("TelegramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TelegramInformationTitle {
            get {
                return ResourceManager.GetString("TelegramInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        internal static string TelegramInvalidNameMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Name.
        /// </summary>
        internal static string TelegramInvalidNameTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you have entered is not valid. Please correct it..
        /// </summary>
        internal static string TelegramInvalidNumberMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        internal static string TelegramInvalidNumberTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load last 10 conversations into Disa..
        /// </summary>
        internal static string TelegramLoadConversations {
            get {
                return ResourceManager.GetString("TelegramLoadConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TelegramName {
            get {
                return ResourceManager.GetString("TelegramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TelegramNext {
            get {
                return ResourceManager.GetString("TelegramNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TelegramNo {
            get {
                return ResourceManager.GetString("TelegramNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram is not Running.
        /// </summary>
        internal static string TelegramNotRunning {
            get {
                return ResourceManager.GetString("TelegramNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string TelegramOkay {
            get {
                return ResourceManager.GetString("TelegramOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string TelegramPhoneNumber {
            get {
                return ResourceManager.GetString("TelegramPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to the internet before running the Setup Wizard..
        /// </summary>
        internal static string TelegramPleaseConnectToInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseConnectToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start Telegram in Disa&apos;s settings..
        /// </summary>
        internal static string TelegramPleaseStart {
            get {
                return ResourceManager.GetString("TelegramPleaseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start Telegram in Disa&apos;s settings, or rerun the setup wizard. If none of these options work, then Telegram is probably down..
        /// </summary>
        internal static string TelegramPleaseStartNoInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseStartNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        internal static string TelegramProfileSettings {
            get {
                return ResourceManager.GetString("TelegramProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram is Running.
        /// </summary>
        internal static string TelegramRunning {
            get {
                return ResourceManager.GetString("TelegramRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Settings.
        /// </summary>
        internal static string TelegramSettingsTitle {
            get {
                return ResourceManager.GetString("TelegramSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Wizard.
        /// </summary>
        internal static string TelegramSetupWizard {
            get {
                return ResourceManager.GetString("TelegramSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Setup Wizard.
        /// </summary>
        internal static string TelegramSetupWizardTitle {
            get {
                return ResourceManager.GetString("TelegramSetupWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string TelegramSubmit {
            get {
                return ResourceManager.GetString("TelegramSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string TelegramVerificationTitle {
            get {
                return ResourceManager.GetString("TelegramVerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Please try again..
        /// </summary>
        internal static string TelegramVerifyError {
            get {
                return ResourceManager.GetString("TelegramVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Have a Code.
        /// </summary>
        internal static string TelegramVerifyHaveCode {
            get {
                return ResourceManager.GetString("TelegramVerifyHaveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number you entered is invalid. Please use another..
        /// </summary>
        internal static string TelegramVerifyInvalidNumber {
            get {
                return ResourceManager.GetString("TelegramVerifyInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to verify your Telegram account?.
        /// </summary>
        internal static string TelegramVerifyQuestion {
            get {
                return ResourceManager.GetString("TelegramVerifyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via Phone.
        /// </summary>
        internal static string TelegramVerifyViaPhone {
            get {
                return ResourceManager.GetString("TelegramVerifyViaPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via SMS.
        /// </summary>
        internal static string TelegramVerifyViaSms {
            get {
                return ResourceManager.GetString("TelegramVerifyViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TelegramYes {
            get {
                return ResourceManager.GetString("TelegramYes", resourceCulture);
            }
        }
    }
}
