// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Disa.Framework.Telegram.Mobile {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Disa.Framework.Telegram.Mobile.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TelegramRunning {
            get {
                return ResourceManager.GetString("TelegramRunning", resourceCulture);
            }
        }
        
        internal static string TelegramNotRunning {
            get {
                return ResourceManager.GetString("TelegramNotRunning", resourceCulture);
            }
        }
        
        internal static string TelegramAllGood {
            get {
                return ResourceManager.GetString("TelegramAllGood", resourceCulture);
            }
        }
        
        internal static string TelegramSettingsTitle {
            get {
                return ResourceManager.GetString("TelegramSettingsTitle", resourceCulture);
            }
        }
        
        internal static string TelegramPleaseStart {
            get {
                return ResourceManager.GetString("TelegramPleaseStart", resourceCulture);
            }
        }
        
        internal static string TelegramPleaseStartNoInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseStartNoInternet", resourceCulture);
            }
        }
        
        internal static string TelegramSetupWizard {
            get {
                return ResourceManager.GetString("TelegramSetupWizard", resourceCulture);
            }
        }
        
        internal static string TelegramProfileSettings {
            get {
                return ResourceManager.GetString("TelegramProfileSettings", resourceCulture);
            }
        }
        
        internal static string TelegramDescription {
            get {
                return ResourceManager.GetString("TelegramDescription", resourceCulture);
            }
        }
        
        internal static string TelegramPleaseConnectToInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseConnectToInternet", resourceCulture);
            }
        }
        
        internal static string TelegramSetupWizardTitle {
            get {
                return ResourceManager.GetString("TelegramSetupWizardTitle", resourceCulture);
            }
        }
        
        internal static string TelegramFirstName {
            get {
                return ResourceManager.GetString("TelegramFirstName", resourceCulture);
            }
        }
        
        internal static string TelegramLastName {
            get {
                return ResourceManager.GetString("TelegramLastName", resourceCulture);
            }
        }
        
        internal static string TelegramLoadConversations {
            get {
                return ResourceManager.GetString("TelegramLoadConversations", resourceCulture);
            }
        }
        
        internal static string TelegramPhoneNumber {
            get {
                return ResourceManager.GetString("TelegramPhoneNumber", resourceCulture);
            }
        }
        
        internal static string TelegramNext {
            get {
                return ResourceManager.GetString("TelegramNext", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidFirstNameTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidFirstNameTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidFirstNameMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidFirstNameMessage", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidLastNameTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidLastNameTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidLastNameMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidLastNameMessage", resourceCulture);
            }
        }
        
        internal static string TelegramOkay {
            get {
                return ResourceManager.GetString("TelegramOkay", resourceCulture);
            }
        }
        
        internal static string TelegramYes {
            get {
                return ResourceManager.GetString("TelegramYes", resourceCulture);
            }
        }
        
        internal static string TelegramNo {
            get {
                return ResourceManager.GetString("TelegramNo", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidNumberTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidNumberMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberMessage", resourceCulture);
            }
        }
        
        internal static string TelegramConfirmNumberTitle {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberTitle", resourceCulture);
            }
        }
        
        internal static string TelegramConfirmNumberMessage {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberMessage", resourceCulture);
            }
        }
        
        internal static string TelegramAuthGenerationFailedMessage {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedMessage", resourceCulture);
            }
        }
        
        internal static string TelegramAuthGenerationFailedTitle {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInformationTitle {
            get {
                return ResourceManager.GetString("TelegramInformationTitle", resourceCulture);
            }
        }
        
        internal static string TelegramVerificationTitle {
            get {
                return ResourceManager.GetString("TelegramVerificationTitle", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyHaveCode {
            get {
                return ResourceManager.GetString("TelegramVerifyHaveCode", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyQuestion {
            get {
                return ResourceManager.GetString("TelegramVerifyQuestion", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyViaPhone {
            get {
                return ResourceManager.GetString("TelegramVerifyViaPhone", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyViaSms {
            get {
                return ResourceManager.GetString("TelegramVerifyViaSms", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyError {
            get {
                return ResourceManager.GetString("TelegramVerifyError", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyInvalidNumber {
            get {
                return ResourceManager.GetString("TelegramVerifyInvalidNumber", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentViaSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaSms", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentViaPhone {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaPhone", resourceCulture);
            }
        }
        
        internal static string TelegramCodeManualEnter {
            get {
                return ResourceManager.GetString("TelegramCodeManualEnter", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentNotComingSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentNotComingSms", resourceCulture);
            }
        }
        
        internal static string TelegramCodeTitle {
            get {
                return ResourceManager.GetString("TelegramCodeTitle", resourceCulture);
            }
        }
        
        internal static string TelegramCode {
            get {
                return ResourceManager.GetString("TelegramCode", resourceCulture);
            }
        }
        
        internal static string TelegramCodeInvalidTitle {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidTitle", resourceCulture);
            }
        }
        
        internal static string TelegramCodeInvalidMessage {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidMessage", resourceCulture);
            }
        }
        
        internal static string TelegramSubmit {
            get {
                return ResourceManager.GetString("TelegramSubmit", resourceCulture);
            }
        }
        
        internal static string TelegramCodeError {
            get {
                return ResourceManager.GetString("TelegramCodeError", resourceCulture);
            }
        }
        
        internal static string TelegramCodeNumberInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeNumberInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramCodeCodeExpired {
            get {
                return ResourceManager.GetString("TelegramCodeCodeExpired", resourceCulture);
            }
        }
        
        internal static string TelegramCodeCodeInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeCodeInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramCodeFirstNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeFirstNameInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramCodeLastNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeLastNameInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramContact {
            get {
                return ResourceManager.GetString("TelegramContact", resourceCulture);
            }
        }
        
        internal static string TelegramEveryone {
            get {
                return ResourceManager.GetString("TelegramEveryone", resourceCulture);
            }
        }
        
        internal static string TelegramGroups {
            get {
                return ResourceManager.GetString("TelegramGroups", resourceCulture);
            }
        }
        
        internal static string TelegramLastSeen {
            get {
                return ResourceManager.GetString("TelegramLastSeen", resourceCulture);
            }
        }
        
        internal static string TelegramNobody {
            get {
                return ResourceManager.GetString("TelegramNobody", resourceCulture);
            }
        }
        
        internal static string TelegramNone {
            get {
                return ResourceManager.GetString("TelegramNone", resourceCulture);
            }
        }
        
        internal static string TelegramNotRunningLong {
            get {
                return ResourceManager.GetString("TelegramNotRunningLong", resourceCulture);
            }
        }
        
        internal static string TelegramPrivacyList {
            get {
                return ResourceManager.GetString("TelegramPrivacyList", resourceCulture);
            }
        }
        
        internal static string TelegramSelect {
            get {
                return ResourceManager.GetString("TelegramSelect", resourceCulture);
            }
        }
    }
}
