// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Disa.Framework.Telegram.Mobile {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Disa.Framework.Telegram.Mobile.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TelegramRunning {
            get {
                return ResourceManager.GetString("TelegramRunning", resourceCulture);
            }
        }
        
        internal static string TelegramNotRunning {
            get {
                return ResourceManager.GetString("TelegramNotRunning", resourceCulture);
            }
        }
        
        internal static string TelegramAllGood {
            get {
                return ResourceManager.GetString("TelegramAllGood", resourceCulture);
            }
        }
        
        internal static string TelegramHelp {
            get {
                return ResourceManager.GetString("TelegramHelp", resourceCulture);
            }
        }
        
        internal static string TelegramSettingsTitle {
            get {
                return ResourceManager.GetString("TelegramSettingsTitle", resourceCulture);
            }
        }
        
        internal static string TelegramPleaseStart {
            get {
                return ResourceManager.GetString("TelegramPleaseStart", resourceCulture);
            }
        }
        
        internal static string TelegramPleaseStartNoInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseStartNoInternet", resourceCulture);
            }
        }
        
        internal static string TelegramSetupWizard {
            get {
                return ResourceManager.GetString("TelegramSetupWizard", resourceCulture);
            }
        }
        
        internal static string TelegramProfileSettings {
            get {
                return ResourceManager.GetString("TelegramProfileSettings", resourceCulture);
            }
        }
        
        internal static string TelegramDescription {
            get {
                return ResourceManager.GetString("TelegramDescription", resourceCulture);
            }
        }
        
        internal static string TelegramPleaseConnectToInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseConnectToInternet", resourceCulture);
            }
        }
        
        internal static string TelegramSetupWizardTitle {
            get {
                return ResourceManager.GetString("TelegramSetupWizardTitle", resourceCulture);
            }
        }
        
        internal static string TelegramFirstName {
            get {
                return ResourceManager.GetString("TelegramFirstName", resourceCulture);
            }
        }
        
        internal static string TelegramLastName {
            get {
                return ResourceManager.GetString("TelegramLastName", resourceCulture);
            }
        }
        
        internal static string TelegramLoadConversations {
            get {
                return ResourceManager.GetString("TelegramLoadConversations", resourceCulture);
            }
        }
        
        internal static string TelegramPhoneNumber {
            get {
                return ResourceManager.GetString("TelegramPhoneNumber", resourceCulture);
            }
        }
        
        internal static string TelegramNext {
            get {
                return ResourceManager.GetString("TelegramNext", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidFirstNameTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidFirstNameTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidFirstNameMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidFirstNameMessage", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidLastNameTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidLastNameTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidLastNameMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidLastNameMessage", resourceCulture);
            }
        }
        
        internal static string TelegramOkay {
            get {
                return ResourceManager.GetString("TelegramOkay", resourceCulture);
            }
        }
        
        internal static string TelegramYes {
            get {
                return ResourceManager.GetString("TelegramYes", resourceCulture);
            }
        }
        
        internal static string TelegramNo {
            get {
                return ResourceManager.GetString("TelegramNo", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidNumberTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidNumberMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberMessage", resourceCulture);
            }
        }
        
        internal static string TelegramConfirmNumberTitle {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberTitle", resourceCulture);
            }
        }
        
        internal static string TelegramConfirmNumberMessage {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberMessage", resourceCulture);
            }
        }
        
        internal static string TelegramAuthGenerationFailedMessage {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedMessage", resourceCulture);
            }
        }
        
        internal static string TelegramAuthGenerationFailedTitle {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedTitle", resourceCulture);
            }
        }
        
        internal static string TelegramInformationTitle {
            get {
                return ResourceManager.GetString("TelegramInformationTitle", resourceCulture);
            }
        }
        
        internal static string TelegramVerificationTitle {
            get {
                return ResourceManager.GetString("TelegramVerificationTitle", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyHaveCode {
            get {
                return ResourceManager.GetString("TelegramVerifyHaveCode", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyQuestion {
            get {
                return ResourceManager.GetString("TelegramVerifyQuestion", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyViaPhone {
            get {
                return ResourceManager.GetString("TelegramVerifyViaPhone", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyViaSms {
            get {
                return ResourceManager.GetString("TelegramVerifyViaSms", resourceCulture);
            }
        }
        
        internal static string TelegramVerifySentToTelegram {
            get {
                return ResourceManager.GetString("TelegramVerifySentToTelegram", resourceCulture);
            }
        }
        
        internal static string TelegramVerifySentViaSms {
            get {
                return ResourceManager.GetString("TelegramVerifySentViaSms", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyError {
            get {
                return ResourceManager.GetString("TelegramVerifyError", resourceCulture);
            }
        }
        
        internal static string TelegramVerifyInvalidNumber {
            get {
                return ResourceManager.GetString("TelegramVerifyInvalidNumber", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentViaSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaSms", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentViaPhone {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaPhone", resourceCulture);
            }
        }
        
        internal static string TelegramCodeManualEnter {
            get {
                return ResourceManager.GetString("TelegramCodeManualEnter", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentNotComingSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentNotComingSms", resourceCulture);
            }
        }
        
        internal static string TelegramCodeTitle {
            get {
                return ResourceManager.GetString("TelegramCodeTitle", resourceCulture);
            }
        }
        
        internal static string TelegramCode {
            get {
                return ResourceManager.GetString("TelegramCode", resourceCulture);
            }
        }
        
        internal static string TelegramCodeInvalidTitle {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidTitle", resourceCulture);
            }
        }
        
        internal static string TelegramCodeInvalidMessage {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidMessage", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidCodeDetail {
            get {
                return ResourceManager.GetString("TelegramInvalidCodeDetail", resourceCulture);
            }
        }
        
        internal static string TelegramSubmit {
            get {
                return ResourceManager.GetString("TelegramSubmit", resourceCulture);
            }
        }
        
        internal static string TelegramCodeError {
            get {
                return ResourceManager.GetString("TelegramCodeError", resourceCulture);
            }
        }
        
        internal static string TelegramCodeNumberInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeNumberInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramCodeCodeExpired {
            get {
                return ResourceManager.GetString("TelegramCodeCodeExpired", resourceCulture);
            }
        }
        
        internal static string TelegramCodeCodeInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeCodeInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramCodeFirstNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeFirstNameInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramCodeLastNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeLastNameInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramContact {
            get {
                return ResourceManager.GetString("TelegramContact", resourceCulture);
            }
        }
        
        internal static string TelegramEveryone {
            get {
                return ResourceManager.GetString("TelegramEveryone", resourceCulture);
            }
        }
        
        internal static string TelegramGroups {
            get {
                return ResourceManager.GetString("TelegramGroups", resourceCulture);
            }
        }
        
        internal static string TelegramLastSeen {
            get {
                return ResourceManager.GetString("TelegramLastSeen", resourceCulture);
            }
        }
        
        internal static string TelegramNobody {
            get {
                return ResourceManager.GetString("TelegramNobody", resourceCulture);
            }
        }
        
        internal static string TelegramNone {
            get {
                return ResourceManager.GetString("TelegramNone", resourceCulture);
            }
        }
        
        internal static string TelegramNotRunningLong {
            get {
                return ResourceManager.GetString("TelegramNotRunningLong", resourceCulture);
            }
        }
        
        internal static string TelegramPrivacyList {
            get {
                return ResourceManager.GetString("TelegramPrivacyList", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentPhoneCall {
            get {
                return ResourceManager.GetString("TelegramCodeSentPhoneCall", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentTelegramApp {
            get {
                return ResourceManager.GetString("TelegramCodeSentTelegramApp", resourceCulture);
            }
        }
        
        internal static string TelegramCodeSentText {
            get {
                return ResourceManager.GetString("TelegramCodeSentText", resourceCulture);
            }
        }
        
        internal static string TelegramCodeResendViaPhoneCall {
            get {
                return ResourceManager.GetString("TelegramCodeResendViaPhoneCall", resourceCulture);
            }
        }
        
        internal static string TelegramCodeResendViaText {
            get {
                return ResourceManager.GetString("TelegramCodeResendViaText", resourceCulture);
            }
        }
        
        internal static string TelegramSelect {
            get {
                return ResourceManager.GetString("TelegramSelect", resourceCulture);
            }
        }
        
        internal static string TelegramVerify {
            get {
                return ResourceManager.GetString("TelegramVerify", resourceCulture);
            }
        }
        
        internal static string TelegramPassword {
            get {
                return ResourceManager.GetString("TelegramPassword", resourceCulture);
            }
        }
        
        internal static string TelegramEnterPassword {
            get {
                return ResourceManager.GetString("TelegramEnterPassword", resourceCulture);
            }
        }
        
        internal static string TelegramPasswordTitle {
            get {
                return ResourceManager.GetString("TelegramPasswordTitle", resourceCulture);
            }
        }
        
        internal static string TelegramFinish {
            get {
                return ResourceManager.GetString("TelegramFinish", resourceCulture);
            }
        }
        
        internal static string TelegramForgotPassword {
            get {
                return ResourceManager.GetString("TelegramForgotPassword", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidPassword {
            get {
                return ResourceManager.GetString("TelegramInvalidPassword", resourceCulture);
            }
        }
        
        internal static string TelegramInvalidPasswordDetail {
            get {
                return ResourceManager.GetString("TelegramInvalidPasswordDetail", resourceCulture);
            }
        }
        
        internal static string TelegramPasswordError {
            get {
                return ResourceManager.GetString("TelegramPasswordError", resourceCulture);
            }
        }
        
        internal static string TelegramCodeIntitalText {
            get {
                return ResourceManager.GetString("TelegramCodeIntitalText", resourceCulture);
            }
        }
        
        internal static string TelegramRecoverPassword {
            get {
                return ResourceManager.GetString("TelegramRecoverPassword", resourceCulture);
            }
        }
        
        internal static string TelegramRecoverPasswordEmail {
            get {
                return ResourceManager.GetString("TelegramRecoverPasswordEmail", resourceCulture);
            }
        }
        
        internal static string TelegramEnterCodeSentToEmail {
            get {
                return ResourceManager.GetString("TelegramEnterCodeSentToEmail", resourceCulture);
            }
        }
        
        internal static string TelegramCannotAccessEmail {
            get {
                return ResourceManager.GetString("TelegramCannotAccessEmail", resourceCulture);
            }
        }
        
        internal static string TelegramCancel {
            get {
                return ResourceManager.GetString("TelegramCancel", resourceCulture);
            }
        }
        
        internal static string TelegramResetAccount {
            get {
                return ResourceManager.GetString("TelegramResetAccount", resourceCulture);
            }
        }
        
        internal static string TelegramNeedToResetAccount {
            get {
                return ResourceManager.GetString("TelegramNeedToResetAccount", resourceCulture);
            }
        }
        
        internal static string TelegramPasswordCodeTitle {
            get {
                return ResourceManager.GetString("TelegramPasswordCodeTitle", resourceCulture);
            }
        }
        
        internal static string TelegramUserInformationTitle {
            get {
                return ResourceManager.GetString("TelegramUserInformationTitle", resourceCulture);
            }
        }
        
        internal static string TelegramUsername {
            get {
                return ResourceManager.GetString("TelegramUsername", resourceCulture);
            }
        }
        
        internal static string TelegramEdit {
            get {
                return ResourceManager.GetString("TelegramEdit", resourceCulture);
            }
        }
        
        internal static string TelegramDone {
            get {
                return ResourceManager.GetString("TelegramDone", resourceCulture);
            }
        }
        
        internal static string TelegramNoUsernameSet {
            get {
                return ResourceManager.GetString("TelegramNoUsernameSet", resourceCulture);
            }
        }
        
        internal static string TelegramEnterUsername {
            get {
                return ResourceManager.GetString("TelegramEnterUsername", resourceCulture);
            }
        }
        
        internal static string TelegramEnterLastName {
            get {
                return ResourceManager.GetString("TelegramEnterLastName", resourceCulture);
            }
        }
        
        internal static string TelegramUserInformation {
            get {
                return ResourceManager.GetString("TelegramUserInformation", resourceCulture);
            }
        }
        
        internal static string TelegramUsernameNotLongEnough {
            get {
                return ResourceManager.GetString("TelegramUsernameNotLongEnough", resourceCulture);
            }
        }
        
        internal static string TelegramUsernameInvalid {
            get {
                return ResourceManager.GetString("TelegramUsernameInvalid", resourceCulture);
            }
        }
        
        internal static string TelegramUsernameTaken {
            get {
                return ResourceManager.GetString("TelegramUsernameTaken", resourceCulture);
            }
        }
        
        internal static string TelegramUsernameAvailable {
            get {
                return ResourceManager.GetString("TelegramUsernameAvailable", resourceCulture);
            }
        }
        
        internal static string TelegramUsernameChecking {
            get {
                return ResourceManager.GetString("TelegramUsernameChecking", resourceCulture);
            }
        }
        
        internal static string TelegramUsernameTryAgainLater {
            get {
                return ResourceManager.GetString("TelegramUsernameTryAgainLater", resourceCulture);
            }
        }
        
        internal static string TelegramNameFirstNameEmpty {
            get {
                return ResourceManager.GetString("TelegramNameFirstNameEmpty", resourceCulture);
            }
        }
        
        internal static string TelegramAlpha {
            get {
                return ResourceManager.GetString("TelegramAlpha", resourceCulture);
            }
        }
    }
}
