// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the SharpTL compiler (https://github.com/Taggersoft/SharpTL).
//     Generated at 08/28/2017 10:14:03
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

#region R#

// ReSharper disable UnusedAutoPropertyAccessor.Global
// ReSharper disable CollectionNeverUpdated.Global
// ReSharper disable UnusedMemberInSuper.Global
// ReSharper disable UnusedParameter.Global
// ReSharper disable UnusedMember.Global
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable InconsistentNaming

#endregion

namespace SharpMTProto.Schema
{
    using SharpTL;
    using System.Threading.Tasks;
    using ProtoBuf;

    // TL constructors.

    [TLObject(0x05162463)]
    [ProtoContract]
    public partial class ResPQ : IResPQ
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.Byte[] Pq { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public System.Collections.Generic.List<System.UInt64> ServerPublicKeyFingerprints { get; set; }

    }

    [TLObject(0x83C95AEC)]
    [ProtoContract]
    public partial class PQInnerData : IPQInnerData
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.Byte[] Pq { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.Byte[] P { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.Byte[] Q { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(5)]
        	[TLProperty(5)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(6)]
        	[TLProperty(6)]
        	public BigMath.Int256 NewNonce { get; set; }

    }

    [TLObject(0x79CB045D)]
    [ProtoContract]
    public partial class ServerDHParamsFail : IServerDHParams
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public BigMath.Int128 NewNonceHash { get; set; }

    }

    [TLObject(0xD0E8075C)]
    [ProtoContract]
    public partial class ServerDHParamsOk : IServerDHParams
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.Byte[] EncryptedAnswer { get; set; }

    }

    [TLObject(0xB5890DBA)]
    [ProtoContract]
    public partial class ServerDHInnerData : IServerDHInnerData
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 G { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public System.Byte[] DhPrime { get; set; }


			[ProtoMember(5)]
        	[TLProperty(5)]
        	public System.Byte[] GA { get; set; }


			[ProtoMember(6)]
        	[TLProperty(6)]
        	public System.UInt32 ServerTime { get; set; }

    }

    [TLObject(0x6643B654)]
    [ProtoContract]
    public partial class ClientDHInnerData : IClientDHInnerData
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt64 RetryId { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public System.Byte[] GB { get; set; }

    }

    [TLObject(0x3BCBF734)]
    [ProtoContract]
    public partial class DhGenOk : ISetClientDHParamsAnswer
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public BigMath.Int128 NewNonceHash1 { get; set; }

    }

    [TLObject(0x46DC1FB9)]
    [ProtoContract]
    public partial class DhGenRetry : ISetClientDHParamsAnswer
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public BigMath.Int128 NewNonceHash2 { get; set; }

    }

    [TLObject(0xA69DAE02)]
    [ProtoContract]
    public partial class DhGenFail : ISetClientDHParamsAnswer
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public BigMath.Int128 NewNonceHash3 { get; set; }

    }

    [TLObject(0xF35C6D01)]
    [ProtoContract]
    public partial class RpcResult : IRpcResult
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 ReqMsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.Object Result { get; set; }

    }

    [TLObject(0x2144CA19)]
    [ProtoContract]
    public partial class RpcError : IRpcError
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt32 ErrorCode { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.String ErrorMessage { get; set; }

    }

    [TLObject(0x5E2AD36E)]
    [ProtoContract]
    public partial class RpcAnswerUnknown : IRpcDropAnswer
    {
    }

    [TLObject(0xCD78E586)]
    [ProtoContract]
    public partial class RpcAnswerDroppedRunning : IRpcDropAnswer
    {
    }

    [TLObject(0xA43AD8B7)]
    [ProtoContract]
    public partial class RpcAnswerDropped : IRpcDropAnswer
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 MsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 SeqNo { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 Bytes { get; set; }

    }

    [TLObject(0x0949D9DC)]
    [ProtoContract]
    public partial class FutureSalt : IFutureSalt
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt32 ValidSince { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 ValidUntil { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt64 Salt { get; set; }

    }

    [TLObject(0xAE500895)]
    [ProtoContract]
    public partial class FutureSalts : IFutureSalts
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 ReqMsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 Now { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3, TLSerializationMode.Bare)]
        	public System.Collections.Generic.List<IFutureSalt> Salts { get; set; }

    }

    [TLObject(0x347773C5)]
    [ProtoContract]
    public partial class Pong : IPong
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 MsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt64 PingId { get; set; }

    }

    [TLObject(0xE22045FC)]
    [ProtoContract]
    public partial class DestroySessionOk : IDestroySessionRes
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 SessionId { get; set; }

    }

    [TLObject(0x62D350C9)]
    [ProtoContract]
    public partial class DestroySessionNone : IDestroySessionRes
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 SessionId { get; set; }

    }

    [TLObject(0x9EC20908)]
    [ProtoContract]
    public partial class NewSessionCreated : INewSession
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 FirstMsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt64 UniqueId { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt64 ServerSalt { get; set; }

    }

    [TLObject(0x73F1F8DC)]
    [ProtoContract]
    public partial class MsgContainer : IMessageContainer
    {

			[ProtoMember(1)]
        	[TLProperty(1, TLSerializationMode.Bare)]
        	public System.Collections.Generic.List<Message> Messages { get; set; }

    }

    [TLObject(0x5BB8E511)]
    [ProtoContract]
    public partial class Message : IMessage
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 MsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 Seqno { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 Bytes { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public System.Object Body { get; set; }

    }

    [TLObject(0xE06046B2)]
    [ProtoContract]
    public partial class MsgCopy : IMessageCopy
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public IMessage OrigMessage { get; set; }

    }

    [TLObject(0x3072CFA1)]
    [ProtoContract]
    public partial class GzipPacked
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.Byte[] PackedData { get; set; }

    }

    [TLObject(0x62D6B459)]
    [ProtoContract]
    public partial class MsgsAck : IMsgsAck
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.Collections.Generic.List<System.UInt64> MsgIds { get; set; }

    }

    [TLObject(0xA7EFF811)]
    [ProtoContract]
    public partial class BadMsgNotification : IBadMsgNotification
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 BadMsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 BadMsgSeqno { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 ErrorCode { get; set; }

    }

    [TLObject(0xEDAB447B)]
    [ProtoContract]
    public partial class BadServerSalt : IBadMsgNotification
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 BadMsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 BadMsgSeqno { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 ErrorCode { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public System.UInt64 NewServerSalt { get; set; }

    }

    [TLObject(0x7D861A08)]
    [ProtoContract]
    public partial class MsgResendReq : IMsgResendReq
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.Collections.Generic.List<System.UInt64> MsgIds { get; set; }

    }

    [TLObject(0xDA69FB52)]
    [ProtoContract]
    public partial class MsgsStateReq : IMsgsStateReq
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.Collections.Generic.List<System.UInt64> MsgIds { get; set; }

    }

    [TLObject(0x04DEB57D)]
    [ProtoContract]
    public partial class MsgsStateInfo : IMsgsStateInfo
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 ReqMsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.Byte[] Info { get; set; }

    }

    [TLObject(0x8CC0D131)]
    [ProtoContract]
    public partial class MsgsAllInfo : IMsgsAllInfo
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.Collections.Generic.List<System.UInt64> MsgIds { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.Byte[] Info { get; set; }

    }

    [TLObject(0x276D3EC6)]
    [ProtoContract]
    public partial class MsgDetailedInfo : IMsgDetailedInfo
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 MsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt64 AnswerMsgId { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 Bytes { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public System.UInt32 Status { get; set; }

    }

    [TLObject(0x809DB6DF)]
    [ProtoContract]
    public partial class MsgNewDetailedInfo : IMsgDetailedInfo
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 AnswerMsgId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 Bytes { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 Status { get; set; }

    }

    [TLObject(0x60469778)]
    [ProtoContract]
    public partial class ReqPqArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }

    }

    [TLObject(0xD712E4BE)]
    [ProtoContract]
    public partial class ReqDHParamsArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.Byte[] P { get; set; }


			[ProtoMember(4)]
        	[TLProperty(4)]
        	public System.Byte[] Q { get; set; }


			[ProtoMember(5)]
        	[TLProperty(5)]
        	public System.UInt64 PublicKeyFingerprint { get; set; }


			[ProtoMember(6)]
        	[TLProperty(6)]
        	public System.Byte[] EncryptedData { get; set; }

    }

    [TLObject(0xF5045F1F)]
    [ProtoContract]
    public partial class SetClientDHParamsArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public BigMath.Int128 Nonce { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public BigMath.Int128 ServerNonce { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.Byte[] EncryptedData { get; set; }

    }

    [TLObject(0x58E4A740)]
    [ProtoContract]
    public partial class RpcDropAnswerArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 ReqMsgId { get; set; }

    }

    [TLObject(0xB921BD04)]
    [ProtoContract]
    public partial class GetFutureSaltsArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt32 Num { get; set; }

    }

    [TLObject(0x7ABE77EC)]
    [ProtoContract]
    public partial class PingArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 PingId { get; set; }

    }

    [TLObject(0xF3427B8C)]
    [ProtoContract]
    public partial class PingDelayDisconnectArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 PingId { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 DisconnectDelay { get; set; }

    }

    [TLObject(0xE7512126)]
    [ProtoContract]
    public partial class DestroySessionArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt64 SessionId { get; set; }

    }

    [TLObject(0x9299359F)]
    [ProtoContract]
    public partial class HttpWaitArgs
    {

			[ProtoMember(1)]
        	[TLProperty(1)]
        	public System.UInt32 MaxDelay { get; set; }


			[ProtoMember(2)]
        	[TLProperty(2)]
        	public System.UInt32 WaitAfter { get; set; }


			[ProtoMember(3)]
        	[TLProperty(3)]
        	public System.UInt32 MaxWait { get; set; }

    }


    // TL types.

    [TLType(typeof(ResPQ))]
    [ProtoContract]
        [ProtoInclude(99,typeof(ResPQ))]
        public partial interface IResPQ
    {
    }

    [TLType(typeof(PQInnerData))]
    [ProtoContract]
        [ProtoInclude(100,typeof(PQInnerData))]
        public partial interface IPQInnerData
    {
    }

    [TLType(typeof(ServerDHParamsFail), typeof(ServerDHParamsOk))]
    [ProtoContract]
        [ProtoInclude(101,typeof(ServerDHParamsFail))]
        [ProtoInclude(102,typeof(ServerDHParamsOk))]
        public partial interface IServerDHParams
    {
    }

    [TLType(typeof(ServerDHInnerData))]
    [ProtoContract]
        [ProtoInclude(103,typeof(ServerDHInnerData))]
        public partial interface IServerDHInnerData
    {
    }

    [TLType(typeof(ClientDHInnerData))]
    [ProtoContract]
        [ProtoInclude(104,typeof(ClientDHInnerData))]
        public partial interface IClientDHInnerData
    {
    }

    [TLType(typeof(DhGenOk), typeof(DhGenRetry), typeof(DhGenFail))]
    [ProtoContract]
        [ProtoInclude(105,typeof(DhGenOk))]
        [ProtoInclude(106,typeof(DhGenRetry))]
        [ProtoInclude(107,typeof(DhGenFail))]
        public partial interface ISetClientDHParamsAnswer
    {
    }

    [TLType(typeof(RpcResult))]
    [ProtoContract]
        [ProtoInclude(108,typeof(RpcResult))]
        public partial interface IRpcResult
    {
    }

    [TLType(typeof(RpcError))]
    [ProtoContract]
        [ProtoInclude(109,typeof(RpcError))]
        public partial interface IRpcError
    {
    }

    [TLType(typeof(RpcAnswerUnknown), typeof(RpcAnswerDroppedRunning), typeof(RpcAnswerDropped))]
    [ProtoContract]
        [ProtoInclude(110,typeof(RpcAnswerUnknown))]
        [ProtoInclude(111,typeof(RpcAnswerDroppedRunning))]
        [ProtoInclude(112,typeof(RpcAnswerDropped))]
        public partial interface IRpcDropAnswer
    {
    }

    [TLType(typeof(FutureSalt))]
    [ProtoContract]
        [ProtoInclude(113,typeof(FutureSalt))]
        public partial interface IFutureSalt
    {
    }

    [TLType(typeof(FutureSalts))]
    [ProtoContract]
        [ProtoInclude(114,typeof(FutureSalts))]
        public partial interface IFutureSalts
    {
    }

    [TLType(typeof(Pong))]
    [ProtoContract]
        [ProtoInclude(115,typeof(Pong))]
        public partial interface IPong
    {
    }

    [TLType(typeof(DestroySessionOk), typeof(DestroySessionNone))]
    [ProtoContract]
        [ProtoInclude(116,typeof(DestroySessionOk))]
        [ProtoInclude(117,typeof(DestroySessionNone))]
        public partial interface IDestroySessionRes
    {
    }

    [TLType(typeof(NewSessionCreated))]
    [ProtoContract]
        [ProtoInclude(118,typeof(NewSessionCreated))]
        public partial interface INewSession
    {
    }

    [TLType(typeof(MsgContainer))]
    [ProtoContract]
        [ProtoInclude(119,typeof(MsgContainer))]
        public partial interface IMessageContainer
    {
    }

    [TLType(typeof(Message))]
    [ProtoContract]
        [ProtoInclude(120,typeof(Message))]
        public partial interface IMessage
    {
    }

    [TLType(typeof(MsgCopy))]
    [ProtoContract]
        [ProtoInclude(121,typeof(MsgCopy))]
        public partial interface IMessageCopy
    {
    }

    [TLType(typeof(MsgsAck))]
    [ProtoContract]
        [ProtoInclude(122,typeof(MsgsAck))]
        public partial interface IMsgsAck
    {
    }

    [TLType(typeof(BadMsgNotification), typeof(BadServerSalt))]
    [ProtoContract]
        [ProtoInclude(123,typeof(BadMsgNotification))]
        [ProtoInclude(124,typeof(BadServerSalt))]
        public partial interface IBadMsgNotification
    {
    }

    [TLType(typeof(MsgResendReq))]
    [ProtoContract]
        [ProtoInclude(125,typeof(MsgResendReq))]
        public partial interface IMsgResendReq
    {
    }

    [TLType(typeof(MsgsStateReq))]
    [ProtoContract]
        [ProtoInclude(126,typeof(MsgsStateReq))]
        public partial interface IMsgsStateReq
    {
    }

    [TLType(typeof(MsgsStateInfo))]
    [ProtoContract]
        [ProtoInclude(127,typeof(MsgsStateInfo))]
        public partial interface IMsgsStateInfo
    {
    }

    [TLType(typeof(MsgsAllInfo))]
    [ProtoContract]
        [ProtoInclude(128,typeof(MsgsAllInfo))]
        public partial interface IMsgsAllInfo
    {
    }

    [TLType(typeof(MsgDetailedInfo), typeof(MsgNewDetailedInfo))]
    [ProtoContract]
        [ProtoInclude(129,typeof(MsgDetailedInfo))]
        [ProtoInclude(130,typeof(MsgNewDetailedInfo))]
        public partial interface IMsgDetailedInfo
    {
    }


    /// <summary>
    ///     TL methods.
    /// </summary>
    public interface IMTProtoMethods
    {
        IResPQ ReqPq(ReqPqArgs args);
        IServerDHParams ReqDHParams(ReqDHParamsArgs args);
        ISetClientDHParamsAnswer SetClientDHParams(SetClientDHParamsArgs args);
        IRpcDropAnswer RpcDropAnswer(RpcDropAnswerArgs args);
        IFutureSalts GetFutureSalts(GetFutureSaltsArgs args);
        IPong Ping(PingArgs args);
        IPong PingDelayDisconnect(PingDelayDisconnectArgs args);
        IDestroySessionRes DestroySession(DestroySessionArgs args);
        void HttpWait(HttpWaitArgs args);
    }

    /// <summary>
    ///     TL async methods.
    /// </summary>
    public interface IMTProtoAsyncMethods
    {
        Task<IResPQ> ReqPqAsync(ReqPqArgs args);
        Task<IServerDHParams> ReqDHParamsAsync(ReqDHParamsArgs args);
        Task<ISetClientDHParamsAnswer> SetClientDHParamsAsync(SetClientDHParamsArgs args);
        Task<IRpcDropAnswer> RpcDropAnswerAsync(RpcDropAnswerArgs args);
        Task<IFutureSalts> GetFutureSaltsAsync(GetFutureSaltsArgs args);
        Task<IPong> PingAsync(PingArgs args);
        Task<IPong> PingDelayDisconnectAsync(PingDelayDisconnectArgs args);
        Task<IDestroySessionRes> DestroySessionAsync(DestroySessionArgs args);
        Task HttpWaitAsync(HttpWaitArgs args);
    }
}
#pragma warning restore 1591
