//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disa.Framework.Telegram {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Disa.Framework.Telegram.ResX.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is looking good..
        /// </summary>
        internal static string TelegramAllGood {
            get {
                return ResourceManager.GetString("TelegramAllGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate an authentication. Please try again..
        /// </summary>
        internal static string TelegramAuthGenerationFailedMessage {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth Generation Failed.
        /// </summary>
        internal static string TelegramAuthGenerationFailedTitle {
            get {
                return ResourceManager.GetString("TelegramAuthGenerationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TelegramCancel {
            get {
                return ResourceManager.GetString("TelegramCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant Access Email?.
        /// </summary>
        internal static string TelegramCannotAccessEmail {
            get {
                return ResourceManager.GetString("TelegramCannotAccessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string TelegramCode {
            get {
                return ResourceManager.GetString("TelegramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered has expired. Please send yourself another..
        /// </summary>
        internal static string TelegramCodeCodeExpired {
            get {
                return ResourceManager.GetString("TelegramCodeCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeCodeInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Please try again..
        /// </summary>
        internal static string TelegramCodeError {
            get {
                return ResourceManager.GetString("TelegramCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeFirstNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeFirstNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the button below to verify your phone number..
        /// </summary>
        internal static string TelegramCodeIntitalText {
            get {
                return ResourceManager.GetString("TelegramCodeIntitalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a code to verify Telegram..
        /// </summary>
        internal static string TelegramCodeInvalidMessage {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Code.
        /// </summary>
        internal static string TelegramCodeInvalidTitle {
            get {
                return ResourceManager.GetString("TelegramCodeInvalidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeLastNameInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeLastNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 6 character code provided from Telegram below..
        /// </summary>
        internal static string TelegramCodeManualEnter {
            get {
                return ResourceManager.GetString("TelegramCodeManualEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number entered is invalid. Please try another..
        /// </summary>
        internal static string TelegramCodeNumberInvalid {
            get {
                return ResourceManager.GetString("TelegramCodeNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t get the code even after a minute? Press the button above to get a call that tells you the code to be entered..
        /// </summary>
        internal static string TelegramCodeResendViaPhoneCall {
            get {
                return ResourceManager.GetString("TelegramCodeResendViaPhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not get the code? Press the button above to recieve the code via SMS..
        /// </summary>
        internal static string TelegramCodeResendViaText {
            get {
                return ResourceManager.GetString("TelegramCodeResendViaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your code does not come through, please click the &apos;Verification&apos; tab and activate Telegram with the &apos;via Phone&apos; option..
        /// </summary>
        internal static string TelegramCodeSentNotComingSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentNotComingSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will get a call from Telegram, which will tell you the code. Enter the code below..
        /// </summary>
        internal static string TelegramCodeSentPhoneCall {
            get {
                return ResourceManager.GetString("TelegramCodeSentPhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code was sent to a Telegram app on your other device.
        /// </summary>
        internal static string TelegramCodeSentTelegramApp {
            get {
                return ResourceManager.GetString("TelegramCodeSentTelegramApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code was sent to you via SMS.
        /// </summary>
        internal static string TelegramCodeSentText {
            get {
                return ResourceManager.GetString("TelegramCodeSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram activation has been contacted! You&apos;ll be phoned shortly with an activation code..
        /// </summary>
        internal static string TelegramCodeSentViaPhone {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram activation has been contacted! You&apos;ll be messaged shortly with an activation code..
        /// </summary>
        internal static string TelegramCodeSentViaSms {
            get {
                return ResourceManager.GetString("TelegramCodeSentViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string TelegramCodeTitle {
            get {
                return ResourceManager.GetString("TelegramCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the number [number] correct? This is what we&apos;ll use to verify your Telegram account..
        /// </summary>
        internal static string TelegramConfirmNumberMessage {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Number.
        /// </summary>
        internal static string TelegramConfirmNumberTitle {
            get {
                return ResourceManager.GetString("TelegramConfirmNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string TelegramContact {
            get {
                return ResourceManager.GetString("TelegramContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram is a messaging app with a focus on speed and security. It&apos;s super-fast, simple, secure and free..
        /// </summary>
        internal static string TelegramDescription {
            get {
                return ResourceManager.GetString("TelegramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string TelegramDone {
            get {
                return ResourceManager.GetString("TelegramDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TelegramEdit {
            get {
                return ResourceManager.GetString("TelegramEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code sent at your recovery email address at [emailPattern]..
        /// </summary>
        internal static string TelegramEnterCodeSentToEmail {
            get {
                return ResourceManager.GetString("TelegramEnterCodeSentToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        internal static string TelegramEnterLastName {
            get {
                return ResourceManager.GetString("TelegramEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password to login.
        /// </summary>
        internal static string TelegramEnterPassword {
            get {
                return ResourceManager.GetString("TelegramEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username.
        /// </summary>
        internal static string TelegramEnterUsername {
            get {
                return ResourceManager.GetString("TelegramEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string TelegramEveryone {
            get {
                return ResourceManager.GetString("TelegramEveryone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string TelegramFinish {
            get {
                return ResourceManager.GetString("TelegramFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string TelegramFirstName {
            get {
                return ResourceManager.GetString("TelegramFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string TelegramForgotPassword {
            get {
                return ResourceManager.GetString("TelegramForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string TelegramGroups {
            get {
                return ResourceManager.GetString("TelegramGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string TelegramHelp {
            get {
                return ResourceManager.GetString("TelegramHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TelegramInformationTitle {
            get {
                return ResourceManager.GetString("TelegramInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code entered is invalid.
        /// </summary>
        internal static string TelegramInvalidCodeDetail {
            get {
                return ResourceManager.GetString("TelegramInvalidCodeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name..
        /// </summary>
        internal static string TelegramInvalidFirstNameMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidFirstNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid First Name.
        /// </summary>
        internal static string TelegramInvalidFirstNameTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidFirstNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name..
        /// </summary>
        internal static string TelegramInvalidLastNameMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidLastNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Last Name.
        /// </summary>
        internal static string TelegramInvalidLastNameTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidLastNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you have entered is not valid. Please correct it..
        /// </summary>
        internal static string TelegramInvalidNumberMessage {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        internal static string TelegramInvalidNumberTitle {
            get {
                return ResourceManager.GetString("TelegramInvalidNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        internal static string TelegramInvalidPassword {
            get {
                return ResourceManager.GetString("TelegramInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered is invalid. Please try again..
        /// </summary>
        internal static string TelegramInvalidPasswordDetail {
            get {
                return ResourceManager.GetString("TelegramInvalidPasswordDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string TelegramLastName {
            get {
                return ResourceManager.GetString("TelegramLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Seen.
        /// </summary>
        internal static string TelegramLastSeen {
            get {
                return ResourceManager.GetString("TelegramLastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load last 10 conversations into Disa..
        /// </summary>
        internal static string TelegramLoadConversations {
            get {
                return ResourceManager.GetString("TelegramLoadConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have Telegram installed! Both Telegram and Disa can be used at the same time. &lt;b&gt;To prevent getting duplicate notifications, please disable Telegram&apos;s notificaions:&lt;/b&gt;.
        /// </summary>
        internal static string TelegramMuteNotificationsHeader {
            get {
                return ResourceManager.GetString("TelegramMuteNotificationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the hamburger button on the main Telegram app screen to open up its menu. Then press &apos;&lt;i&gt;Settings&lt;/i&gt;,&apos; followed by &apos;&lt;i&gt;Notifications and Sounds&lt;/i&gt;.&apos; Disable the two &apos;&lt;i&gt;Alert&lt;/i&gt;&apos; toggles under &apos;&lt;i&gt;Message notifications&lt;/i&gt;&apos; and &apos;&lt;i&gt;Group notifications&lt;/i&gt;.&apos;.
        /// </summary>
        internal static string TelegramMuteNotificationsStep1Text {
            get {
                return ResourceManager.GetString("TelegramMuteNotificationsStep1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How?.
        /// </summary>
        internal static string TelegramMuteNotificationsStep1Title {
            get {
                return ResourceManager.GetString("TelegramMuteNotificationsStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Notifications.
        /// </summary>
        internal static string TelegramMuteNotificationsTitle {
            get {
                return ResourceManager.GetString("TelegramMuteNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Video.
        /// </summary>
        internal static string TelegramMuteNotificationsWatchVideo {
            get {
                return ResourceManager.GetString("TelegramMuteNotificationsWatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first name cannot be empty..
        /// </summary>
        internal static string TelegramNameFirstNameEmpty {
            get {
                return ResourceManager.GetString("TelegramNameFirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cant access your email, the only option you have is to reset your account. WARNING! Clicking the okay button will delete all your chats and data from the Telegram servers. .
        /// </summary>
        internal static string TelegramNeedToResetAccount {
            get {
                return ResourceManager.GetString("TelegramNeedToResetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TelegramNext {
            get {
                return ResourceManager.GetString("TelegramNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TelegramNo {
            get {
                return ResourceManager.GetString("TelegramNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody.
        /// </summary>
        internal static string TelegramNobody {
            get {
                return ResourceManager.GetString("TelegramNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string TelegramNone {
            get {
                return ResourceManager.GetString("TelegramNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram is not Running.
        /// </summary>
        internal static string TelegramNotRunning {
            get {
                return ResourceManager.GetString("TelegramNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram needs to be running before you can adjust its profile settings..
        /// </summary>
        internal static string TelegramNotRunningLong {
            get {
                return ResourceManager.GetString("TelegramNotRunningLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username set.
        /// </summary>
        internal static string TelegramNoUsernameSet {
            get {
                return ResourceManager.GetString("TelegramNoUsernameSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string TelegramOkay {
            get {
                return ResourceManager.GetString("TelegramOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string TelegramPassword {
            get {
                return ResourceManager.GetString("TelegramPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery Code.
        /// </summary>
        internal static string TelegramPasswordCodeTitle {
            get {
                return ResourceManager.GetString("TelegramPasswordCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Please try again..
        /// </summary>
        internal static string TelegramPasswordError {
            get {
                return ResourceManager.GetString("TelegramPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string TelegramPasswordTitle {
            get {
                return ResourceManager.GetString("TelegramPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string TelegramPhoneNumber {
            get {
                return ResourceManager.GetString("TelegramPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to the internet before running the Setup Wizard..
        /// </summary>
        internal static string TelegramPleaseConnectToInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseConnectToInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start Telegram in Disa&apos;s settings..
        /// </summary>
        internal static string TelegramPleaseStart {
            get {
                return ResourceManager.GetString("TelegramPleaseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please start Telegram in Disa&apos;s settings, or rerun the setup wizard. If none of these options work, then Telegram is probably down..
        /// </summary>
        internal static string TelegramPleaseStartNoInternet {
            get {
                return ResourceManager.GetString("TelegramPleaseStartNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy List.
        /// </summary>
        internal static string TelegramPrivacyList {
            get {
                return ResourceManager.GetString("TelegramPrivacyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        internal static string TelegramProfileSettings {
            get {
                return ResourceManager.GetString("TelegramProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string TelegramRecoverPassword {
            get {
                return ResourceManager.GetString("TelegramRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Recovery.
        /// </summary>
        internal static string TelegramRecoverPasswordEmail {
            get {
                return ResourceManager.GetString("TelegramRecoverPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Account.
        /// </summary>
        internal static string TelegramResetAccount {
            get {
                return ResourceManager.GetString("TelegramResetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram is Running.
        /// </summary>
        internal static string TelegramRunning {
            get {
                return ResourceManager.GetString("TelegramRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type contact name.
        /// </summary>
        internal static string TelegramSearchHint {
            get {
                return ResourceManager.GetString("TelegramSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string TelegramSelect {
            get {
                return ResourceManager.GetString("TelegramSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Settings.
        /// </summary>
        internal static string TelegramSettingsTitle {
            get {
                return ResourceManager.GetString("TelegramSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Wizard.
        /// </summary>
        internal static string TelegramSetupWizard {
            get {
                return ResourceManager.GetString("TelegramSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram Setup Wizard.
        /// </summary>
        internal static string TelegramSetupWizardTitle {
            get {
                return ResourceManager.GetString("TelegramSetupWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string TelegramSubmit {
            get {
                return ResourceManager.GetString("TelegramSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use a-z, 0-9 and underscores. Minimum length is 5 characters..
        /// </summary>
        internal static string TelegramUserInformation {
            get {
                return ResourceManager.GetString("TelegramUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        internal static string TelegramUserInformationTitle {
            get {
                return ResourceManager.GetString("TelegramUserInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string TelegramUsername {
            get {
                return ResourceManager.GetString("TelegramUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [username] is available!.
        /// </summary>
        internal static string TelegramUsernameAvailable {
            get {
                return ResourceManager.GetString("TelegramUsernameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking username....
        /// </summary>
        internal static string TelegramUsernameChecking {
            get {
                return ResourceManager.GetString("TelegramUsernameChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this username is invalid..
        /// </summary>
        internal static string TelegramUsernameInvalid {
            get {
                return ResourceManager.GetString("TelegramUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username must have at least 5 characters..
        /// </summary>
        internal static string TelegramUsernameNotLongEnough {
            get {
                return ResourceManager.GetString("TelegramUsernameNotLongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this username is already taken..
        /// </summary>
        internal static string TelegramUsernameTaken {
            get {
                return ResourceManager.GetString("TelegramUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later....
        /// </summary>
        internal static string TelegramUsernameTryAgainLater {
            get {
                return ResourceManager.GetString("TelegramUsernameTryAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string TelegramVerificationTitle {
            get {
                return ResourceManager.GetString("TelegramVerificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string TelegramVerify {
            get {
                return ResourceManager.GetString("TelegramVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured. Please try again..
        /// </summary>
        internal static string TelegramVerifyError {
            get {
                return ResourceManager.GetString("TelegramVerifyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Have a Code.
        /// </summary>
        internal static string TelegramVerifyHaveCode {
            get {
                return ResourceManager.GetString("TelegramVerifyHaveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number you entered is invalid. Please use another..
        /// </summary>
        internal static string TelegramVerifyInvalidNumber {
            get {
                return ResourceManager.GetString("TelegramVerifyInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to verify your Telegram account?.
        /// </summary>
        internal static string TelegramVerifyQuestion {
            get {
                return ResourceManager.GetString("TelegramVerifyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code was sent to the Telegram app on your other device.
        /// </summary>
        internal static string TelegramVerifySentToTelegram {
            get {
                return ResourceManager.GetString("TelegramVerifySentToTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code was sent via SMS to .
        /// </summary>
        internal static string TelegramVerifySentViaSms {
            get {
                return ResourceManager.GetString("TelegramVerifySentViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via Phone.
        /// </summary>
        internal static string TelegramVerifyViaPhone {
            get {
                return ResourceManager.GetString("TelegramVerifyViaPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via SMS.
        /// </summary>
        internal static string TelegramVerifyViaSms {
            get {
                return ResourceManager.GetString("TelegramVerifyViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TelegramYes {
            get {
                return ResourceManager.GetString("TelegramYes", resourceCulture);
            }
        }
    }
}
